name: ForUTN Github Action CI Develop
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - feature
  pull_request:
    branches:
      - develop


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: |
        AZURE_STORAGE_CONNECTION_STRING=$AZURE_STORAGE_CONNECTION_STRING
        DB_USER=$DB_USER
        DB_PWD=$DB_PWD
        DB_PORT=$DB_PORT
        DB_HOST=$DB_HOST
        DB_DBNAME=$DB_DBNAME
        npm i
        npm test
      env:
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PWD: ${{ secrets.DB_PWD }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_DBNAME: ${{ secrets.DB_DBNAME }}
      